name: Lint Code

on: [push, pull_request]

permissions: {}

jobs:
  build:
    name: Lint Code
    runs-on: ubuntu-latest
    
    permissions: 
      contents: read
      packages: read
      statuses: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v1
        with:
          fetch-depth: 0
      
      - name: Lint Code
        uses: super-linter/super-linter@v7.4.0
        env:
          VALIDATE_ALL_CODEBASE: true
          VALIDATE_PYTHON_RUFF: true
          VALIDATE_PYTHON_FLAKE8: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
